-- Crear base de datos
CREATE DATABASE online_store;

-- Cambiar a la base de datos recién creada (comando para psql)
-- \c online_store

-- 1. Tabla: categorías
CREATE TABLE categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255)
);

-- 2. Tabla: estados de orden
CREATE TABLE order_status (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255)
);

-- 3. Tabla: usuarios administradores
CREATE TABLE admin_users (
  id UUID PRIMARY KEY,
  full_name VARCHAR(255),
  status BOOLEAN,
  email VARCHAR(255) UNIQUE,
  password_hash TEXT,
  create_at TIMESTAMPTZ DEFAULT now(),
  update_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Tabla: clientes
CREATE TABLE customers (
  id UUID PRIMARY KEY,
  name VARCHAR(100),
  last_name VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  phone VARCHAR(15),
  status BOOLEAN,
  username VARCHAR(100) UNIQUE,
  password_hash VARCHAR(255),
  create_at TIMESTAMPTZ DEFAULT now(),
  update_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Tabla: productos
CREATE TABLE products (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(1000),
  price NUMERIC(10,2),
  image_url VARCHAR(1000),
  category_id INT REFERENCES categories(id),
  status BOOLEAN,
  create_at TIMESTAMPTZ DEFAULT now(),
  update_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Tabla: stock de productos
CREATE TABLE product_stock (
  product_id INT PRIMARY KEY REFERENCES products(id),
  quantity INT
);

-- 7. Tabla: direcciones de clientes
CREATE TABLE customer_addresses (
  id UUID PRIMARY KEY,
  customer_id UUID REFERENCES customers(id),
  address VARCHAR(500),
  city VARCHAR(50),
  postal_code VARCHAR(20),
  is_default BOOLEAN,
  title VARCHAR(100),
  create_at TIMESTAMPTZ DEFAULT now(),
  update_at TIMESTAMPTZ DEFAULT now()
);

-- 8. Tabla: métodos de pago del cliente
CREATE TABLE customer_payment_methods (
  id UUID PRIMARY KEY,
  customer_id UUID REFERENCES customers(id),
  type VARCHAR(50),
  account_last4 VARCHAR(4),
  token TEXT,
  is_default BOOLEAN,
  create_at TIMESTAMPTZ DEFAULT now(),
  provider VARCHAR(100)
);

-- 9. Tabla: órdenes
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id UUID REFERENCES customers(id),
  address_id UUID REFERENCES customer_addresses(id),
  total_amount NUMERIC(10,2),
  order_status_id INT REFERENCES order_status(id),
  create_at TIMESTAMPTZ DEFAULT now()
);

-- 10. Tabla: productos en órdenes
CREATE TABLE order_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id),
  product_id INT REFERENCES products(id),
  quantity INT,
  unit_price NUMERIC(10,2)
);

-- 11. Tabla: pagos de órdenes
CREATE TABLE payments_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id),
  payment_method VARCHAR(100),
  amount NUMERIC(10,2),
  status VARCHAR(20),
  processed_at TIMESTAMPTZ DEFAULT now()
);

-- 12. Tabla: registros de actividad de administradores
CREATE TABLE admin_activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id UUID REFERENCES admin_users(id),
  action VARCHAR(20),
  entity_name VARCHAR(100),
  entity_id UUID,
  description TEXT,
  changes JSONB,
  create_at TIMESTAMPTZ DEFAULT now()
);


INSERT INTO categories (title) VALUES
  ('Ropa'),
  ('Electrodomésticos'),
  ('Tecnología'),
  ('Hogar y Decoración'),
  ('Juguetes'),
  ('Otros');